pipeline {
    agent any

    environment {
        COMPOSE_FILE = 'docker-compose.yml'
        PROJECT_NAME = 'chatapp'
        BACKEND_DIR = 'backend'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/duykhanhdeveloper93/chatApp3'
            }
        }

        stage('Generate Migration') {
            steps {
                dir("${BACKEND_DIR}") {
                    sh '''
                        echo "📦 Cài dependency..."
                        npm install

                        echo "📂 Nạp biến môi trường từ .env..."
                        export $(grep -v '^#' .env | xargs)

                        MIGRATION_NAME="AutoGenerated$(date +%s)"
                        echo "🧠 Sinh migration mới: $MIGRATION_NAME"

                        npx ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:generate \
                            -d data-source.ts src/migrations/$MIGRATION_NAME \
                            || echo "⚠️ Không có thay đổi nào để generate"
                    '''
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh '''
                    echo "⚙️ Đang build Docker images..."
                    docker-compose -p $PROJECT_NAME -f $COMPOSE_FILE build
                '''
            }
        }

        stage('Deploy & Run Migration') {
            steps {
                sh '''
                    echo "🧹 Xóa container cũ..."
                    docker-compose -p $PROJECT_NAME -f $COMPOSE_FILE down --remove-orphans || true
                    docker ps -a --filter "name=${PROJECT_NAME}" -q | xargs -r docker rm -f || true
                    docker ps -a --filter "name=chat-" -q | xargs -r docker rm -f || true

                    echo "🚀 Khởi động container mới..."
                    docker-compose -p $PROJECT_NAME -f $COMPOSE_FILE up -d

                    echo "⚙️ Chạy migration trong container backend..."
                    docker exec ${PROJECT_NAME}-backend-1 npx typeorm migration:run -d dist/data-source.js \
                        || echo "⚠️ Không có migration nào để chạy"
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Triển khai thành công!'
        }
        failure {
            echo '❌ Triển khai thất bại!'
        }
    }
}
