pipeline {
    agent any

    environment {
        COMPOSE_FILE = 'docker-compose.yml'
        PROJECT_NAME = 'chatapp'
        BACKEND_DIR = 'backend'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/duykhanhdeveloper93/chatApp3'
            }
        }

        stage('Start DB for Migration') {
            steps {
                sh '''
                    echo "🐳 Khởi động tạm MySQL container..."
                    docker-compose -p $PROJECT_NAME -f $COMPOSE_FILE up -d mysql

                    echo "⏳ Chờ MySQL khởi động..."
                    sleep 15
                '''
            }
        }

        stage('Generate Migration Inside Backend Container') {
            steps {
                sh '''
                    echo "🐳 Khởi động tạm backend container để sinh migration..."
                    docker-compose -p $PROJECT_NAME -f $COMPOSE_FILE up -d backend

                    echo "🕒 Đợi backend container khởi động ổn định..."

                    # Thử chờ backend healthy (nếu có healthcheck)
                    for i in $(seq 1 15); do
                        STATUS=$(docker inspect -f {{.State.Health.Status}} chat-backend 2>/dev/null || echo "starting")
                        if [ "$STATUS" = "healthy" ]; then
                            echo "✅ Backend healthy!"
                            break
                        fi
                        echo "⏳ Backend chưa sẵn sàng ($i/15)..."
                        sleep 3
                    done

                    echo "🧠 Sinh migration mới..."
                    MIGRATION_NAME="AutoGenerated$(date +%s)"

                    docker exec chat-backend npx ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:generate \
                        -d src/data-source.ts src/migrations/$MIGRATION_NAME \
                        || echo "⚠️ Không có thay đổi nào để generate"

                    echo "🧹 Dừng container tạm..."
                    docker-compose -p $PROJECT_NAME -f $COMPOSE_FILE down || true
                '''
            }
        }

        stage('Rebuild & Deploy') {
            steps {
                sh '''
                    echo "🚀 Build & khởi động lại toàn bộ project..."
                    docker-compose -p $PROJECT_NAME -f $COMPOSE_FILE up -d --build

                    echo "⏳ Đợi backend khởi động để chạy migration..."
                    sleep 15

                    echo "⚙️ Chạy migration trong container backend..."
                    docker exec chat-backend npx typeorm migration:run -d dist/data-source.js \
                        || echo "⚠️ Không có migration nào để chạy"
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Triển khai thành công!'
        }
        failure {
            echo '❌ Triển khai thất bại!'
        }
    }
}
